version: "2"
checks:
  method-complexity:
    config:
      threshold: 10
  method-lines:
    config:
      threshold: 50
plugins:
  rubocop:
    enabled: true
exclude_patterns:
  - "config/"
  - "db/"
  - "dist/"
  - "features/"
  - "**/node_modules/"
  - "script/"
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - "Tests/"
  - "**/vendor/"
  - "**/*_test.go"
  - "**/*.d.ts"
