language: ruby

rvm:
  - 2.6

env:
  - DB=mysql

branches:
  only:
    - master

cache: bundler

script:
  - cd docroot
  - RAILS_ENV=test bundle exec rake db:test:prepare
  - RAILS_ENV=test bundle exec rspec spec/

before_script:
  - mysql -e 'create database commonplace_test'
