env:
  global:
    - CC_TEST_REPORTER_ID=9229f6f974dfbacd71cf3d6ce4e14600fbe25fc3d5dea3e64c190f6070be1481

language: ruby

rvm:
  - 2.6

services:
  - mysql

branches:
  only:
    - main
    - staging

gemfile: docroot/Gemfile

cache: bundler

before_script:
  - mysql -e 'create database commonplace_test'
  - cd docroot
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - RAILS_ENV=test bundle exec rake db:test:prepare
  - RAILS_ENV=test bundle exec rspec spec/

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
