version: "2.4"

services:
  db:
    image: mysql:5.7
    container_name: commonplace-db
    working_dir: /home/app/docroot
    restart: always
    mem_limit: 1g
    cpu_percent: 50
    cpu_shares: 1024
    pids_limit: 100
    volumes:
      - ./docroot:/home/app/docroot:cached
      - ./db-backups:/var/mysql/backups:delegated
      - ./docker/provision/mysql/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "127.0.0.1:3311:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 15s
      interval: 5m
      retries: 5

  web:
    build: .
    working_dir: /home/app/docroot
    container_name: commonplace-web
    restart: always
    mem_limit: 1g
    cpu_percent: 50
    cpu_shares: 1024
    pids_limit: 200
    env_file:
      - .env
    ports:
      - "127.0.0.1:8085:80"
    links:
      - db
    volumes:
      - ./docroot:/home/app/docroot:cached
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost" ]
      timeout: 5s
      interval: 5m
      retries: 5
