source "https://rubygems.org"

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem "rails", "~> 5.1.4"
# Use sqlite3 as the database for Active Record
gem "sqlite3"
# Use Puma as the app server
gem "puma", "~> 3.7"
# Use SCSS for stylesheets
gem "sass-rails", "~> 5.0"
# Use Uglifier as compressor for JavaScript assets
gem "uglifier", ">= 1.3.0"
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use CoffeeScript for .coffee assets and views
gem "coffee-rails", "~> 4.2"
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem "jbuilder", "~> 2.5"
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'
gem "mechanize"
gem "kindle-highlights",
  :git => "https://github.com/bdlangton/kindle-highlights.git",
  :branch => "add-notes"
gem "bundler"
gem "fileutils"
gem "json"
gem "mail"
gem "htmlentities"
gem "jquery-rails"
gem "jquery-ui-rails"
gem "mysql2", "< 0.5"
gem "autoprefixer-rails"
gem "will_paginate"
gem "font-awesome-rails"
gem "bootstrap"
gem "will_paginate-bootstrap4"
gem "devise"
gem "rails-jquery-autocomplete"
gem "chosen-rails"
gem "actionview", ">= 5.1.6.2"
gem "nokogiri", ">= 1.10.4"

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem "byebug", platforms: [:mri, :mingw, :x64_mingw]
  # Adds support for Capybara system testing and selenium driver
  gem "capybara"
  gem "selenium-webdriver"
  gem "better_errors"
  gem "binding_of_caller"
  gem "pry-rails"
  gem "factory_bot_rails"
  gem "rspec-rails"
  gem "activerecord"
  gem "database_cleaner"
  gem "simplecov"
  gem "simplecov-console"
  gem "rufo"
  gem "rubocop"
  gem "reek"
  gem "rubocop-rails_config"
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem "web-console", ">= 3.3.0"
  gem "listen", ">= 3.0.5", "< 3.2"
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem "spring"
  gem "spring-watcher-listen", "~> 2.0.0"
end

gem "tzinfo-data"
